services:
  api:
    build: ../
    container_name: expressCommerce
    ports:
      - '8000:8000'
    networks:
      - expressCommerce-network
    env_file:
      - ../.env.production
networks:
  expressCommerce-network:
    driver: bridge
