# version: '3.8'
services:
  consul-server1:
    image: hashicorp/consul:1.14.4
    container_name: consul-server1
    hostname: consul-server1
    restart: always
    volumes:
      - ./vault/consul/server1/config:/vault/consul/config
      - ./vault/consul/server1/data:/vault/consul/data
    ports:
      - '8500:8500'
      - '8600:8600/tcp'
      - '8600:8600/udp'
    command: 'agent -server -bootstrap-expect=3 -ui -client=0.0.0.0'
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_CLIENT_INTERFACE: eth0

  consul-server2:
    image: hashicorp/consul:1.14.4
    container_name: consul-server2
    hostname: consul-server2
    restart: always
    volumes:
      - ./vault/consul/server2/config:/vault/consul/config
      - ./vault/consul/server2/data:/vault/consul/data
    command: 'agent -server -retry-join=consul-server1 -client=0.0.0.0'
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_CLIENT_INTERFACE: eth0
    depends_on:
      - consul-server1

  consul-server3:
    image: hashicorp/consul:1.14.4
    container_name: consul-server3
    hostname: consul-server3
    restart: always
    volumes:
      - ./vault/consul/server3/config:/vault/consul/config
      - ./vault/consul/server3/data:/vault/consul/data
    command: 'agent -server -retry-join=consul-server1 -client=0.0.0.0'
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_CLIENT_INTERFACE: eth0
    depends_on:
      - consul-server1

  # Vault service
  vault:
    image: vault:1.13.3
    container_name: vault
    hostname: vault
    restart: always
    command: server
    volumes:
      - vault-logs:/vault/logs
      - ./vault/config:/vault/config
    environment:
      VAULT_ADDR: 'https://127.0.0.1:8200'
    cap_add:
      - IPC_LOCK
    ports:
      - '8200:8200'
      - '8201:8201'
    depends_on:
      - consul-server1
      - consul-server2
      - consul-server3

volumes:
  vault-logs:
